title: ""
email: contact@claytownsend.com.au
tagline: "See my Work:"
description: "Clay Townsend - Landing Page"
github_username:  yokoszn
twitter_username: yokoszn

baseurl: ""
url: "https://yokoszn.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - help.md
  - services.md
  - tos.md
  - privacy.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
